# This is the default list of blocks used by the game.
# Blocks can be added to or removed from this list.

blocks:
  - STONE
  - GRANITE
  - POLISHED_GRANITE
  - DIORITE
  - POLISHED_DIORITE
  - ANDESITE
  - POLISHED_ANDESITE
  - DEEPSLATE
  - COBBLED_DEEPSLATE
  - POLISHED_DEEPSLATE
  - CALCITE
  - TUFF
  - DRIPSTONE_BLOCK
  - GRASS_BLOCK
  - DIRT
  - COARSE_DIRT
  - COBBLESTONE
  - OAK_PLANKS
  - SPRUCE_PLANKS
  - BIRCH_PLANKS
  - ACACIA_PLANKS
  - DARK_OAK_PLANKS
  - OAK_SAPLING
  - SPRUCE_SAPLING
  - BIRCH_SAPLING
  - ACACIA_SAPLING
  - DARK_OAK_SAPLING
  - SAND
  - GRAVEL
  - COAL_ORE
  - DEEPSLATE_COAL_ORE
  - IRON_ORE
  - DEEPSLATE_IRON_ORE
  - COPPER_ORE
  - DEEPSLATE_COPPER_ORE
  - GOLD_ORE
  - DEEPSLATE_GOLD_ORE
  - REDSTONE_ORE
  - DEEPSLATE_REDSTONE_ORE
  - LAPIS_ORE
  - DEEPSLATE_LAPIS_ORE
  - DEEPSLATE_DIAMOND_ORE
  - COAL_BLOCK
  - RAW_IRON_BLOCK
  - RAW_COPPER_BLOCK
  - OAK_LOG
  - SPRUCE_LOG
  - BIRCH_LOG
  - ACACIA_LOG
  - DARK_OAK_LOG
  - STRIPPED_OAK_LOG
  - STRIPPED_SPRUCE_LOG
  - STRIPPED_BIRCH_LOG
  - STRIPPED_ACACIA_LOG
  - STRIPPED_DARK_OAK_LOG
  - STRIPPED_OAK_WOOD
  - STRIPPED_SPRUCE_WOOD
  - STRIPPED_BIRCH_WOOD
  - STRIPPED_ACACIA_WOOD
  - STRIPPED_DARK_OAK_WOOD
  - OAK_WOOD
  - SPRUCE_WOOD
  - BIRCH_WOOD
  - ACACIA_WOOD
  - DARK_OAK_WOOD
  - OAK_LEAVES
  - SPRUCE_LEAVES
  - BIRCH_LEAVES
  - ACACIA_LEAVES
  - DARK_OAK_LEAVES
  - AZALEA_LEAVES
  - FLOWERING_AZALEA_LEAVES
  - GLASS
  - SANDSTONE
  - CHISELED_SANDSTONE
  - CUT_SANDSTONE
  - COBWEB
  - GRASS
  - FERN
  - AZALEA
  - FLOWERING_AZALEA
  - DEAD_BUSH
  - SEAGRASS
  - WHITE_WOOL
  - ORANGE_WOOL
  - MAGENTA_WOOL
  - LIGHT_BLUE_WOOL
  - YELLOW_WOOL
  - LIME_WOOL
  - PINK_WOOL
  - GRAY_WOOL
  - LIGHT_GRAY_WOOL
  - CYAN_WOOL
  - PURPLE_WOOL
  - BLUE_WOOL
  - GREEN_WOOL
  - RED_WOOL
  - BLACK_WOOL
  - DANDELION
  - POPPY
  - ALLIUM
  - AZURE_BLUET
  - RED_TULIP
  - ORANGE_TULIP
  - WHITE_TULIP
  - PINK_TULIP
  - OXEYE_DAISY
  - CORNFLOWER
  - LILY_OF_THE_VALLEY
  - BROWN_MUSHROOM
  - RED_MUSHROOM
  - SUGAR_CANE
  - KELP
  - MOSS_CARPET
  - MOSS_BLOCK
  - OAK_SLAB
  - SPRUCE_SLAB
  - BIRCH_SLAB
  - ACACIA_SLAB
  - DARK_OAK_SLAB
  - STONE_SLAB
  - SMOOTH_STONE_SLAB
  - SANDSTONE_SLAB
  - CUT_SANDSTONE_SLAB
  - COBBLESTONE_SLAB
  - BRICK_SLAB
  - STONE_BRICK_SLAB
  - BRICKS
  - BOOKSHELF
  - OBSIDIAN
  - TORCH
  - CHEST
  - CRAFTING_TABLE
  - FARMLAND
  - FURNACE
  - LADDER
  - COBBLESTONE_STAIRS
  - CLAY
  - JUKEBOX
  - OAK_FENCE
  - SPRUCE_FENCE
  - BIRCH_FENCE
  - ACACIA_FENCE
  - DARK_OAK_FENCE
  - PUMPKIN
  - CARVED_PUMPKIN
  - JACK_O_LANTERN
  - STONE_BRICKS
  - CRACKED_STONE_BRICKS
  - CHISELED_STONE_BRICKS
  - DEEPSLATE_BRICKS
  - CRACKED_DEEPSLATE_BRICKS
  - DEEPSLATE_TILES
  - CRACKED_DEEPSLATE_TILES
  - CHISELED_DEEPSLATE
  - BROWN_MUSHROOM_BLOCK
  - RED_MUSHROOM_BLOCK
  - MUSHROOM_STEM
  - IRON_BARS
  - CHAIN
  - GLASS_PANE
  - MELON
  - VINE
  - GLOW_LICHEN
  - BRICK_STAIRS
  - STONE_BRICK_STAIRS
  - MYCELIUM
  - LILY_PAD
  - SANDSTONE_STAIRS
  - OAK_STAIRS
  - SPRUCE_STAIRS
  - BIRCH_STAIRS
  - ACACIA_STAIRS
  - DARK_OAK_STAIRS
  - COBBLESTONE_WALL
  - BRICK_WALL
  - GRANITE_WALL
  - STONE_BRICK_WALL
  - ANDESITE_WALL
  - SANDSTONE_WALL
  - DIORITE_WALL
  - COBBLED_DEEPSLATE_WALL
  - POLISHED_DEEPSLATE_WALL
  - DEEPSLATE_BRICK_WALL
  - DEEPSLATE_TILE_WALL
  - HAY_BLOCK
  - WHITE_CARPET
  - ORANGE_CARPET
  - MAGENTA_CARPET
  - LIGHT_BLUE_CARPET
  - YELLOW_CARPET
  - LIME_CARPET
  - PINK_CARPET
  - GRAY_CARPET
  - LIGHT_GRAY_CARPET
  - CYAN_CARPET
  - PURPLE_CARPET
  - BLUE_CARPET
  - GREEN_CARPET
  - RED_CARPET
  - BLACK_CARPET
  - TERRACOTTA
  - DIRT_PATH
  - LILAC
  - ROSE_BUSH
  - PEONY
  - TALL_GRASS
  - LARGE_FERN
  - WHITE_STAINED_GLASS
  - ORANGE_STAINED_GLASS
  - MAGENTA_STAINED_GLASS
  - LIGHT_BLUE_STAINED_GLASS
  - YELLOW_STAINED_GLASS
  - LIME_STAINED_GLASS
  - PINK_STAINED_GLASS
  - GRAY_STAINED_GLASS
  - LIGHT_GRAY_STAINED_GLASS
  - CYAN_STAINED_GLASS
  - PURPLE_STAINED_GLASS
  - BLUE_STAINED_GLASS
  - GREEN_STAINED_GLASS
  - RED_STAINED_GLASS
  - BLACK_STAINED_GLASS
  - WHITE_STAINED_GLASS_PANE
  - ORANGE_STAINED_GLASS_PANE
  - MAGENTA_STAINED_GLASS_PANE
  - LIGHT_BLUE_STAINED_GLASS_PANE
  - YELLOW_STAINED_GLASS_PANE
  - LIME_STAINED_GLASS_PANE
  - PINK_STAINED_GLASS_PANE
  - GRAY_STAINED_GLASS_PANE
  - LIGHT_GRAY_STAINED_GLASS_PANE
  - CYAN_STAINED_GLASS_PANE
  - PURPLE_STAINED_GLASS_PANE
  - BLUE_STAINED_GLASS_PANE
  - GREEN_STAINED_GLASS_PANE
  - RED_STAINED_GLASS_PANE
  - BLACK_STAINED_GLASS_PANE
  - MAGMA_BLOCK
  - BONE_BLOCK
  - WHITE_CONCRETE
  - ORANGE_CONCRETE
  - MAGENTA_CONCRETE
  - LIGHT_BLUE_CONCRETE
  - YELLOW_CONCRETE
  - LIME_CONCRETE
  - PINK_CONCRETE
  - GRAY_CONCRETE
  - LIGHT_GRAY_CONCRETE
  - CYAN_CONCRETE
  - PURPLE_CONCRETE
  - BLUE_CONCRETE
  - GREEN_CONCRETE
  - RED_CONCRETE
  - BLACK_CONCRETE
  - WHITE_CONCRETE_POWDER
  - ORANGE_CONCRETE_POWDER
  - MAGENTA_CONCRETE_POWDER
  - LIGHT_BLUE_CONCRETE_POWDER
  - YELLOW_CONCRETE_POWDER
  - LIME_CONCRETE_POWDER
  - PINK_CONCRETE_POWDER
  - GRAY_CONCRETE_POWDER
  - LIGHT_GRAY_CONCRETE_POWDER
  - CYAN_CONCRETE_POWDER
  - PURPLE_CONCRETE_POWDER
  - BLUE_CONCRETE_POWDER
  - GREEN_CONCRETE_POWDER
  - RED_CONCRETE_POWDER
  - BLACK_CONCRETE_POWDER
  - POLISHED_GRANITE_STAIRS
  - POLISHED_DIORITE_STAIRS
  - STONE_STAIRS
  - SMOOTH_SANDSTONE_STAIRS
  - GRANITE_STAIRS
  - ANDESITE_STAIRS
  - POLISHED_ANDESITE_STAIRS
  - DIORITE_STAIRS
  - COBBLED_DEEPSLATE_STAIRS
  - POLISHED_DEEPSLATE_STAIRS
  - DEEPSLATE_BRICK_STAIRS
  - DEEPSLATE_TILE_STAIRS
  - POLISHED_GRANITE_SLAB
  - POLISHED_DIORITE_SLAB
  - SMOOTH_SANDSTONE_SLAB
  - GRANITE_SLAB
  - ANDESITE_SLAB
  - POLISHED_ANDESITE_SLAB
  - DIORITE_SLAB
  - COBBLED_DEEPSLATE_SLAB
  - POLISHED_DEEPSLATE_SLAB
  - DEEPSLATE_BRICK_SLAB
  - DEEPSLATE_TILE_SLAB
  - REDSTONE_TORCH
  - REDSTONE_BLOCK
  - REPEATER
  - COMPARATOR
  - PISTON
  - HOPPER
  - DISPENSER
  - DROPPER
  - LECTERN
  - TARGET
  - LEVER
  - LIGHTNING_ROD
  - TRIPWIRE_HOOK
  - TRAPPED_CHEST
  - TNT
  - NOTE_BLOCK
  - STONE_BUTTON
  - OAK_BUTTON
  - SPRUCE_BUTTON
  - BIRCH_BUTTON
  - ACACIA_BUTTON
  - DARK_OAK_BUTTON
  - STONE_PRESSURE_PLATE
  - LIGHT_WEIGHTED_PRESSURE_PLATE
  - HEAVY_WEIGHTED_PRESSURE_PLATE
  - OAK_PRESSURE_PLATE
  - SPRUCE_PRESSURE_PLATE
  - BIRCH_PRESSURE_PLATE
  - ACACIA_PRESSURE_PLATE
  - DARK_OAK_PRESSURE_PLATE
  - IRON_DOOR
  - OAK_DOOR
  - SPRUCE_DOOR
  - BIRCH_DOOR
  - ACACIA_DOOR
  - DARK_OAK_DOOR
  - IRON_TRAPDOOR
  - OAK_TRAPDOOR
  - SPRUCE_TRAPDOOR
  - BIRCH_TRAPDOOR
  - ACACIA_TRAPDOOR
  - DARK_OAK_TRAPDOOR
  - OAK_FENCE_GATE
  - SPRUCE_FENCE_GATE
  - BIRCH_FENCE_GATE
  - ACACIA_FENCE_GATE
  - DARK_OAK_FENCE_GATE
  - POWERED_RAIL
  - DETECTOR_RAIL
  - RAIL
  - ACTIVATOR_RAIL
  - WHEAT
  - OAK_SIGN
  - SPRUCE_SIGN
  - BIRCH_SIGN
  - ACACIA_SIGN
  - DARK_OAK_SIGN
  - DRIED_KELP_BLOCK
  - WHITE_BED
  - ORANGE_BED
  - MAGENTA_BED
  - LIGHT_BLUE_BED
  - YELLOW_BED
  - LIME_BED
  - PINK_BED
  - GRAY_BED
  - LIGHT_GRAY_BED
  - CYAN_BED
  - PURPLE_BED
  - BLUE_BED
  - GREEN_BED
  - RED_BED
  - BLACK_BED
  - CAULDRON
  - FLOWER_POT
  - WHITE_BANNER
  - ORANGE_BANNER
  - MAGENTA_BANNER
  - LIGHT_BLUE_BANNER
  - YELLOW_BANNER
  - LIME_BANNER
  - PINK_BANNER
  - GRAY_BANNER
  - LIGHT_GRAY_BANNER
  - CYAN_BANNER
  - PURPLE_BANNER
  - BLUE_BANNER
  - GREEN_BANNER
  - RED_BANNER
  - BLACK_BANNER
  - LOOM
  - COMPOSTER
  - BARREL
  - SMOKER
  - BLAST_FURNACE
  - CARTOGRAPHY_TABLE
  - FLETCHING_TABLE
  - GRINDSTONE
  - SMITHING_TABLE
  - STONECUTTER
  - BELL
  - LANTERN
  - CAMPFIRE
  - BEE_NEST
  - POINTED_DRIPSTONE
  - WATER
  - TALL_SEAGRASS
  - FIRE
  - REDSTONE_WIRE
  - SWEET_BERRY_BUSH